name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Descargar última versión de la imagen
        working-directory: ./PROYECTOS/despliegue
        run: |
          sudo docker-compose -f Docker.Compose.yml pull entrena-sync-exercises-microservice

      - name: Deploy con docker-compose (working-directory)
        working-directory: ./PROYECTOS/despliegue
        run: sudo docker-compose -f Docker.Compose.yml --env-file .env.apigetaway up -d entrena-sync-exercises-microservice --build